alias clion="/opt/clion-2017.2.3/bin/clion.sh"
alias goland="/opt/GoLand-2017.3/bin/goland.sh"
alias webstorm="/opt/WebStorm-173.4548.30/bin/webstorm.sh"
alias net-ufmg="sudo wpa_supplicant -c/etc/netctl/wlp3s0-ufmg -i wlp3s0"
alias net-home="sudo netctl start wlp3s0-NetV404"
alias net-tracksale="sudo netctl start wlp3s0-Tracksale"
alias net-dcc="sudo wpa_supplicant -c/etc/netctl/wlp3s0-dcc -i wlp3s0"
